BEGIN TRANSACTION;
insert into coaches(name) values ('(Владивосток)');
insert into coaches(name) values ('(Находка)');
insert into coaches(name) values ('(Уссурийск)');
insert into coaches(name) values ('(Хабаровск)');
insert into coaches(name) values ('(Юж. Сахалинск)');
insert into coaches(name) values ('Алексеев Павел Сергеевич');
insert into coaches(name) values ('Аникушин А.А.');
insert into coaches(name) values ('Аникушкин');
insert into coaches(name) values ('Блоцкий А.В.');
insert into coaches(name) values ('Боев Виктор Семенович');
insert into coaches(name) values ('Бордюгов Виталий Николаевич');
insert into coaches(name) values ('Бородий Юрий Иванович');
insert into coaches(name) values ('Булгакова М.Н.');
insert into coaches(name) values ('Волченков А.В.');
insert into coaches(name) values ('Грищенко М.А.');
insert into coaches(name) values ('Давыденко О.В.');
insert into coaches(name) values ('Давыдов В.П.');
insert into coaches(name) values ('Ершов Анатолий Александрович');
insert into coaches(name) values ('Завертайленко А.А.');
insert into coaches(name) values ('Зайкин А.С.');
insert into coaches(name) values ('Закойщиков А.В.');
insert into coaches(name) values ('Зотник А.С.');
insert into coaches(name) values ('Иванов');
insert into coaches(name) values ('Иванов Вячеслав Юрьевич');
insert into coaches(name) values ('Исаков А.Г.');
insert into coaches(name) values ('Калманов М.Б.');
insert into coaches(name) values ('Караульных К');
insert into coaches(name) values ('Караульных К.А.');
insert into coaches(name) values ('Каюмов И.Н.');
insert into coaches(name) values ('Келехсаев Р.У.');
insert into coaches(name) values ('Климчук А.А.');
insert into coaches(name) values ('Клочков С.В.');
insert into coaches(name) values ('Коваленко С.О.');
insert into coaches(name) values ('Ковалёв В.С.');
insert into coaches(name) values ('Колбасин А.А.');
insert into coaches(name) values ('Колесников С.А.');
insert into coaches(name) values ('Комиссаренко Е.В.');
insert into coaches(name) values ('Коротков Ю.А.');
insert into coaches(name) values ('Крат Виталий Петрович');
insert into coaches(name) values ('Кузнецов Р.И.');
insert into coaches(name) values ('Лазарев');
insert into coaches(name) values ('Лазарев Евгений Игоревич');
insert into coaches(name) values ('Лазарев Е.Л.');
insert into coaches(name) values ('Лазарева Ю.Б.');
insert into coaches(name) values ('Леоновец');
insert into coaches(name) values ('Леоновец Максим Сергеевич');
insert into coaches(name) values ('Леоновец Роман Сергеевич');
insert into coaches(name) values ('Луценко Э.А.');
insert into coaches(name) values ('Мореходов А.А.');
insert into coaches(name) values ('Мунтяну П.М.');
insert into coaches(name) values ('Наймушин С. Ю.');
insert into coaches(name) values ('Накагава О.А.');
insert into coaches(name) values ('Паламарчук');
insert into coaches(name) values ('Паламарчук А.');
insert into coaches(name) values ('Паламарчук А.В.');
insert into coaches(name) values ('Паламарчук Я.В.');
insert into coaches(name) values ('Петров В.В.');
insert into coaches(name) values ('Печников В.В.');
insert into coaches(name) values ('Плещук С.Ж.');
insert into coaches(name) values ('Полещук');
insert into coaches(name) values ('Полещук Семен Жоржевич');
insert into coaches(name) values ('Попов Павел В');
insert into coaches(name) values ('Порубов С.Ф.');
insert into coaches(name) values ('Резепкин Владимир Николаевич');
insert into coaches(name) values ('Романов Р.Н.');
insert into coaches(name) values ('Сашко Александр Валерьевич');
insert into coaches(name) values ('Светайло В.Д.');
insert into coaches(name) values ('Сергеев');
insert into coaches(name) values ('Сергеев Александр Садофович');
insert into coaches(name) values ('Сивопляс Денис Анатольевич');
insert into coaches(name) values ('Со Андрей Николаевич');
insert into coaches(name) values ('Тихонов С.В.');
insert into coaches(name) values ('Тюкалов Д.С.');
insert into coaches(name) values ('Хлыновский Д.Ю.');
insert into coaches(name) values ('Цейзик Р.В.');
insert into coaches(name) values ('Цихмистров ');
insert into coaches(name) values ('Цихмистров Максим Леонидович');
insert into coaches(name) values ('Чернышов А.А.');
insert into coaches(name) values ('Чжан В.В.');
insert into coaches(name) values ('Шаломаев Е.А.');
COMMIT;
